version: "3.9"

services:
  gcode-gizmos-frontend:
    image: gcode-gizmos-frontend/gcode-gizmos-frontend:latest
    env_file:
      - .env
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gcode-gizmos-frontend.rule=Host(`gcode-gizmos.${PRIMARY_DOMAIN}`)"
      - "traefik.http.routers.gcode-gizmos-frontend.entrypoints=websecure"
      - "traefik.http.routers.gcode-gizmos-frontend.tls.certresolver=le"
    networks:
      - root_traefik-public
networks:
  root_traefik-public:
    external: true